# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: BTP
on:
  push:
    branches:
      - main
jobs:
  build-test-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{secrets.GH_PAT}}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm ci    
      - name: Run tests
        run: npm test
      - name: Run examples
        run: npm run examples
      - name: Build package
        run: npm run build
      - name: Configure deploy package
        run: |
          npm version patch --git-tag-version false
          cat package.json > ./dist/package.json
          cat README.md > ./dist/README.md
          cat .npmrc > ./dist/.npmrc
          cat LICENSE > ./dist/LICENSE
      - name: Publish package
        run: npm publish
        working-directory: dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
      - name: Bump version
        run: |
          PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
          git config user.name "github-actions[bot]"
          git config --global user.email "username@users.noreply.github.com"
          git add .
          git commit -m "[skip ci] Bumping version package to $PACKAGE_VERSION"
          git push